// Auto-generated by backend/scripts/v2/deploy.js. Commit this file.
export const V2_CONTRACT_ADDRESSES = {
    "CUSD": "0x7D5Dbda57E186f7e905e5E77224Cd60054fF41f3",
    "NameRegistry": "0x1c8fCc121D52EAa6d4705fCcE95e34E2CEDced5E",
    "ChainCircleCoreV2": "0xd0105BC643EadFc8312211e0e4B35c36CEbec7e2",
    "ReputationManagerV2": "0xF75fEc00ea81b31893E3C3C195A46bC2D4BeAcEB",
    "BadgeNFTV2": "0x8044ce1AE0e40C28b1b4869110a01842f5155523",
    "WalletPreferencesV2": "0xd74eFA9343028bbbc864aE42aac8b11373C9b813",
    "GovernanceModuleV2": "0x8dAac1b0dbC0B5561768658b2d99be3129318dD2",
    "TestnetYield": "0x8Bf15ce481eA106beC3540C44D5A154caBcd03C1"
};
export const V2_DEPLOY_BLOCK = 13762869;
export const V2_NETWORK = {"name":"pushDonut","chainId":42101};
